### ISSUE TITLE
Warning: WordPress could not establish a secure connection to WordPress.org

### ISSUE THREAD

**Issue by parallelus** [parallelus/Runway-Framework#108]
This warning is appearing for a user reporting it in different places at different times. I don't think it's specific to any particular area of Runway, but could be caused by the code that checks for updates. If that is making the request take too long I think it's possible for this warning to show. 

> Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.)

The posts referencing this error:

http://runwaywp.com/support/topic/missing-style-css-file/#post-3343
http://runwaywp.com/support/topic/new-parsing-error/

I think it's going to be difficult to reproduce the warning so we may have to do unit testing to see the time it is taking to do update checks instead.

**Comment by parallelus** [comment]
I've upgraded this to medium priority.

**Comment by lesninsky** [comment]
I could get the server's response one time only after this error  (wp-includes/update.php, line 457) - "name lookup timed out" ( please see the fragment of screenshot).

![screenshot from 2015-02-06 12 36 54](https://cloud.githubusercontent.com/assets/1948539/6079873/8e9cc576-ae13-11e4-9b11-433ed5730101.png)

This is response, which returned the request https://api.wordpress.org/themes/update-check/1.1/. Perhaps the reason is a segment of user's network, that's why in order to reduce the network loading a user can try to turn off in Screen Options the options "Wordpress News" and "Right Now in Forums".

I am not sure that our update theme functionality is related to this issue, anyway I have increased timeout for wp_remote_post() reques and added an additional checking.

**Comment by parallelus** [comment]
I'm going to close this one until we get additional feedback. If any new information is discovered we can reopen it and investigate again. Thanks for checking into this!
