### ISSUE TITLE
Set default value or Select default value for Image Radio Button, MultiSelect, CheckBox List

### ISSUE THREAD

**Issue by minhcanhdn** [parallelus/Runway-Framework#160]
I need set default value (or select default value) for Image Radio Button, MultiSelect, CheckBox List. Please help or guide me how to do it.

**Comment by parallelus** [comment]
Creating an option in the select such as `default=>Default` is a method I have used. In the code, when I retrieve that value, if it is set to my first "default" option it can be substituted with some standard setting. For example:

```
$my_select = get_options_data('options-page', 'my-select');
$select_value = ( $my_select == 'default' ) ? 'a default value' : $my_select;
```

Using that you can plugin the value set by the user and if not set it will use the default specified by you. This is also a very good way to ensure you have some error checking in the code so that when a theme is first installed it will have settings even if the user has never accessed or saved the theme options from the admin.
